version: '3.8'

services:
  elysiavernight-journal:
    build:
      context: .
      dockerfile: Dockerfile
    image: elysivernight-journal:latest
    container_name: elysiavernight-journal
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.journal-backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.journal-backend.entrypoints=websecure"
      - "traefik.http.routers.journal-backend.tls.certresolver=myresolver"
      - "traefik.http.services.journal-backend.loadbalancer.server.port=7000"
    networks:
      - elysia-network

networks:
  elysia-network:
    external: true